#!/bin/sh

echo
echo "#"
echo "# simle run of sdc-parser to check one file"
echo "#"
echo "# command line: sdcparser.tcl tests/dc_risc_core.sdc"
echo "#"
echo 


../sdcparser.tcl ../tests/dc_risc_core.sdc


echo
echo "# end"
echo
