#!/bin/sh

echo
echo "#"
echo "# run of sdc-parser to check one file"
echo "# with enabling EDA callback procedure"
echo "#"
echo "# command line: eda_sample.tcl tests/dc_risc_core.sdc"
echo "#"
echo 

rm -f eda_result.sdc

../eda_sample.tcl ../tests/dc_risc_core.sdc |more

echo
echo "# end"
echo
