#!/bin/sh

echo
echo "#"
echo "# run of sdc-parser to check one file"
echo "# with another sdc version"
echo "#"
echo "# command line: sdcparser.tcl tests/dc_risc_core.sdc"
echo "#"
echo 


../sdcparser.tcl ../tests/test_for_sdc_1.2.sdc


echo
echo "# end"
echo
