#!/bin/sh

echo
echo "#"
echo "# run of sdc-parser to check one file"
echo "# without showing any error messages"
echo "#"
echo "# command line: sdcparser.tcl -d0 tests/dc_risc_core.sdc"
echo "#"
echo 


../sdcparser.tcl -d0 ../tests/dc_risc_core.sdc


echo
echo "# end"
echo
